"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class ScreenReaders(Enum):
    """Utilities for improving accessibility with screen readers.
    Tailwind documentation URL: https://tailwindcss.com/docs/screen-readers"""
    SR_ONLY = "sr-only"
    NOT_SR_ONLY = "not-sr-only"

