"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class BoxShadow(Enum):
    """Utilities for controlling the box shadow of an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/box-shadow"""
    SHADOW_SM = "shadow-sm"
    SHADOW = "shadow"
    SHADOW_MD = "shadow-md"
    SHADOW_LG = "shadow-lg"
    SHADOW_XL = "shadow-xl"
    SHADOW_2XL = "shadow-2xl"
    SHADOW_INNER = "shadow-inner"
    SHADOW_NONE = "shadow-none"


class Opacity(Enum):
    """Utilities for controlling the opacity of an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/opacity"""
    OPACITY_0 = "opacity-0"
    OPACITY_5 = "opacity-5"
    OPACITY_10 = "opacity-10"
    OPACITY_20 = "opacity-20"
    OPACITY_25 = "opacity-25"
    OPACITY_30 = "opacity-30"
    OPACITY_40 = "opacity-40"
    OPACITY_50 = "opacity-50"
    OPACITY_60 = "opacity-60"
    OPACITY_70 = "opacity-70"
    OPACITY_75 = "opacity-75"
    OPACITY_80 = "opacity-80"
    OPACITY_90 = "opacity-90"
    OPACITY_95 = "opacity-95"
    OPACITY_100 = "opacity-100"


class MixBlendMode(Enum):
    """Utilities for controlling how an element should blend with the background.
    Tailwind documentation URL: https://tailwindcss.com/docs/mix-blend-mode"""
    MIX_BLEND_NORMAL = "mix-blend-normal"
    MIX_BLEND_MULTIPLY = "mix-blend-multiply"
    MIX_BLEND_SCREEN = "mix-blend-screen"
    MIX_BLEND_OVERLAY = "mix-blend-overlay"
    MIX_BLEND_DARKEN = "mix-blend-darken"
    MIX_BLEND_LIGHTEN = "mix-blend-lighten"
    MIX_BLEND_COLOR_DODGE = "mix-blend-color-dodge"
    MIX_BLEND_COLOR_BURN = "mix-blend-color-burn"
    MIX_BLEND_HARD_LIGHT = "mix-blend-hard-light"
    MIX_BLEND_SOFT_LIGHT = "mix-blend-soft-light"
    MIX_BLEND_DIFFERENCE = "mix-blend-difference"
    MIX_BLEND_EXCLUSION = "mix-blend-exclusion"
    MIX_BLEND_HUE = "mix-blend-hue"
    MIX_BLEND_SATURATION = "mix-blend-saturation"
    MIX_BLEND_COLOR = "mix-blend-color"
    MIX_BLEND_LUMINOSITY = "mix-blend-luminosity"


class BackgroundBlendMode(Enum):
    """Utilities for controlling how an element's background image should blend with its background color.
    Tailwind documentation URL: https://tailwindcss.com/docs/background-blend-mode"""
    BG_BLEND_NORMAL = "bg-blend-normal"
    BG_BLEND_MULTIPLY = "bg-blend-multiply"
    BG_BLEND_SCREEN = "bg-blend-screen"
    BG_BLEND_OVERLAY = "bg-blend-overlay"
    BG_BLEND_DARKEN = "bg-blend-darken"
    BG_BLEND_LIGHTEN = "bg-blend-lighten"
    BG_BLEND_COLOR_DODGE = "bg-blend-color-dodge"
    BG_BLEND_COLOR_BURN = "bg-blend-color-burn"
    BG_BLEND_HARD_LIGHT = "bg-blend-hard-light"
    BG_BLEND_SOFT_LIGHT = "bg-blend-soft-light"
    BG_BLEND_DIFFERENCE = "bg-blend-difference"
    BG_BLEND_EXCLUSION = "bg-blend-exclusion"
    BG_BLEND_HUE = "bg-blend-hue"
    BG_BLEND_SATURATION = "bg-blend-saturation"
    BG_BLEND_COLOR = "bg-blend-color"
    BG_BLEND_LUMINOSITY = "bg-blend-luminosity"

