"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class Filter(Enum):
    """Utilities for enabling and disabling filters on an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/filter"""
    FILTER = "filter"
    FILTER_NONE = "filter-none"


class Blur(Enum):
    """Utilities for applying blur filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/blur"""
    BLUR_NONE = "blur-none"
    BLUR_SM = "blur-sm"
    BLUR = "blur"
    BLUR_MD = "blur-md"
    BLUR_LG = "blur-lg"
    BLUR_XL = "blur-xl"
    BLUR_2XL = "blur-2xl"
    BLUR_3XL = "blur-3xl"


class Brightness(Enum):
    """Utilities for applying brightness filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/brightness"""
    BRIGHTNESS_0 = "brightness-0"
    BRIGHTNESS_50 = "brightness-50"
    BRIGHTNESS_75 = "brightness-75"
    BRIGHTNESS_90 = "brightness-90"
    BRIGHTNESS_95 = "brightness-95"
    BRIGHTNESS_100 = "brightness-100"
    BRIGHTNESS_105 = "brightness-105"
    BRIGHTNESS_110 = "brightness-110"
    BRIGHTNESS_125 = "brightness-125"
    BRIGHTNESS_150 = "brightness-150"
    BRIGHTNESS_200 = "brightness-200"


class Contrast(Enum):
    """Utilities for applying contrast filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/contrast"""
    CONTRAST_0 = "contrast-0"
    CONTRAST_50 = "contrast-50"
    CONTRAST_75 = "contrast-75"
    CONTRAST_100 = "contrast-100"
    CONTRAST_125 = "contrast-125"
    CONTRAST_150 = "contrast-150"
    CONTRAST_200 = "contrast-200"


class DropShadow(Enum):
    """Utilities for applying drop-shadow filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/drop-shadow"""
    DROP_SHADOW_SM = "drop-shadow-sm"
    DROP_SHADOW = "drop-shadow"
    DROP_SHADOW_MD = "drop-shadow-md"
    DROP_SHADOW_LG = "drop-shadow-lg"
    DROP_SHADOW_XL = "drop-shadow-xl"
    DROP_SHADOW_2XL = "drop-shadow-2xl"
    DROP_SHADOW_NONE = "drop-shadow-none"


class Grayscale(Enum):
    """Utilities for applying grayscale filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/grayscale"""
    GRAYSCALE_0 = "grayscale-0"
    GRAYSCALE = "grayscale"


class HueRotate(Enum):
    """Utilities for applying hue-rotate filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/hue-rotate"""
    _HUE_ROTATE_180 = "-hue-rotate-180"
    _HUE_ROTATE_90 = "-hue-rotate-90"
    _HUE_ROTATE_60 = "-hue-rotate-60"
    _HUE_ROTATE_30 = "-hue-rotate-30"
    _HUE_ROTATE_15 = "-hue-rotate-15"
    HUE_ROTATE_0 = "hue-rotate-0"
    HUE_ROTATE_15 = "hue-rotate-15"
    HUE_ROTATE_30 = "hue-rotate-30"
    HUE_ROTATE_60 = "hue-rotate-60"
    HUE_ROTATE_90 = "hue-rotate-90"
    HUE_ROTATE_180 = "hue-rotate-180"


class Invert(Enum):
    """Utilities for applying invert filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/invert"""
    INVERT_0 = "invert-0"
    INVERT = "invert"


class Saturate(Enum):
    """Utilities for applying saturation filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/saturate"""
    SATURATE_0 = "saturate-0"
    SATURATE_50 = "saturate-50"
    SATURATE_100 = "saturate-100"
    SATURATE_150 = "saturate-150"
    SATURATE_200 = "saturate-200"


class Sepia(Enum):
    """Utilities for applying sepia filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/sepia"""
    SEPIA_0 = "sepia-0"
    SEPIA = "sepia"


class BackdropFilter(Enum):
    """Utilities for enabling and disabling backdrop filters on an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-filter"""
    BACKDROP_FILTER = "backdrop-filter"
    BACKDROP_FILTER_NONE = "backdrop-filter-none"


class BackdropBlur(Enum):
    """Utilities for applying backdrop blur filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-blur"""
    BACKDROP_BLUR_NONE = "backdrop-blur-none"
    BACKDROP_BLUR_SM = "backdrop-blur-sm"
    BACKDROP_BLUR = "backdrop-blur"
    BACKDROP_BLUR_MD = "backdrop-blur-md"
    BACKDROP_BLUR_LG = "backdrop-blur-lg"
    BACKDROP_BLUR_XL = "backdrop-blur-xl"
    BACKDROP_BLUR_2XL = "backdrop-blur-2xl"
    BACKDROP_BLUR_3XL = "backdrop-blur-3xl"


class BackdropBrightness(Enum):
    """Utilities for applying backdrop brightness filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-brightness"""
    BACKDROP_BRIGHTNESS_0 = "backdrop-brightness-0"
    BACKDROP_BRIGHTNESS_50 = "backdrop-brightness-50"
    BACKDROP_BRIGHTNESS_75 = "backdrop-brightness-75"
    BACKDROP_BRIGHTNESS_90 = "backdrop-brightness-90"
    BACKDROP_BRIGHTNESS_95 = "backdrop-brightness-95"
    BACKDROP_BRIGHTNESS_100 = "backdrop-brightness-100"
    BACKDROP_BRIGHTNESS_105 = "backdrop-brightness-105"
    BACKDROP_BRIGHTNESS_110 = "backdrop-brightness-110"
    BACKDROP_BRIGHTNESS_125 = "backdrop-brightness-125"
    BACKDROP_BRIGHTNESS_150 = "backdrop-brightness-150"
    BACKDROP_BRIGHTNESS_200 = "backdrop-brightness-200"


class BackdropContrast(Enum):
    """Utilities for applying backdrop contrast filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-contrast"""
    BACKDROP_CONTRAST_0 = "backdrop-contrast-0"
    BACKDROP_CONTRAST_50 = "backdrop-contrast-50"
    BACKDROP_CONTRAST_75 = "backdrop-contrast-75"
    BACKDROP_CONTRAST_100 = "backdrop-contrast-100"
    BACKDROP_CONTRAST_125 = "backdrop-contrast-125"
    BACKDROP_CONTRAST_150 = "backdrop-contrast-150"
    BACKDROP_CONTRAST_200 = "backdrop-contrast-200"


class BackdropGrayscale(Enum):
    """Utilities for applying backdrop grayscale filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-grayscale"""
    BACKDROP_GRAYSCALE_0 = "backdrop-grayscale-0"
    BACKDROP_GRAYSCALE = "backdrop-grayscale"


class BackdropHueRotate(Enum):
    """Utilities for applying backdrop hue-rotate filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-hue-rotate"""
    _BACKDROP_HUE_ROTATE_180 = "-backdrop-hue-rotate-180"
    _BACKDROP_HUE_ROTATE_90 = "-backdrop-hue-rotate-90"
    _BACKDROP_HUE_ROTATE_60 = "-backdrop-hue-rotate-60"
    _BACKDROP_HUE_ROTATE_30 = "-backdrop-hue-rotate-30"
    _BACKDROP_HUE_ROTATE_15 = "-backdrop-hue-rotate-15"
    BACKDROP_HUE_ROTATE_0 = "backdrop-hue-rotate-0"
    BACKDROP_HUE_ROTATE_15 = "backdrop-hue-rotate-15"
    BACKDROP_HUE_ROTATE_30 = "backdrop-hue-rotate-30"
    BACKDROP_HUE_ROTATE_60 = "backdrop-hue-rotate-60"
    BACKDROP_HUE_ROTATE_90 = "backdrop-hue-rotate-90"
    BACKDROP_HUE_ROTATE_180 = "backdrop-hue-rotate-180"


class BackdropInvert(Enum):
    """Utilities for applying backdrop invert filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-invert"""
    BACKDROP_INVERT_0 = "backdrop-invert-0"
    BACKDROP_INVERT = "backdrop-invert"


class BackdropOpacity(Enum):
    """Utilities for applying backdrop opacity filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-opacity"""
    BACKDROP_OPACITY_0 = "backdrop-opacity-0"
    BACKDROP_OPACITY_5 = "backdrop-opacity-5"
    BACKDROP_OPACITY_10 = "backdrop-opacity-10"
    BACKDROP_OPACITY_20 = "backdrop-opacity-20"
    BACKDROP_OPACITY_25 = "backdrop-opacity-25"
    BACKDROP_OPACITY_30 = "backdrop-opacity-30"
    BACKDROP_OPACITY_40 = "backdrop-opacity-40"
    BACKDROP_OPACITY_50 = "backdrop-opacity-50"
    BACKDROP_OPACITY_60 = "backdrop-opacity-60"
    BACKDROP_OPACITY_70 = "backdrop-opacity-70"
    BACKDROP_OPACITY_75 = "backdrop-opacity-75"
    BACKDROP_OPACITY_80 = "backdrop-opacity-80"
    BACKDROP_OPACITY_90 = "backdrop-opacity-90"
    BACKDROP_OPACITY_95 = "backdrop-opacity-95"
    BACKDROP_OPACITY_100 = "backdrop-opacity-100"


class BackdropSaturate(Enum):
    """Utilities for applying backdrop saturation filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-saturate"""
    BACKDROP_SATURATE_0 = "backdrop-saturate-0"
    BACKDROP_SATURATE_50 = "backdrop-saturate-50"
    BACKDROP_SATURATE_100 = "backdrop-saturate-100"
    BACKDROP_SATURATE_150 = "backdrop-saturate-150"
    BACKDROP_SATURATE_200 = "backdrop-saturate-200"


class BackdropSepia(Enum):
    """Utilities for applying backdrop sepia filters to an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/backdrop-sepia"""
    BACKDROP_SEPIA_0 = "backdrop-sepia-0"
    BACKDROP_SEPIA = "backdrop-sepia"

