"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class Appearance(Enum):
    """Utilities for suppressing native form control styling.
    Tailwind documentation URL: https://tailwindcss.com/docs/appearance"""
    APPEARANCE_NONE = "appearance-none"


class Cursor(Enum):
    """Utilities for controlling the cursor style when hovering over an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/cursor"""
    CURSOR_AUTO = "cursor-auto"
    CURSOR_DEFAULT = "cursor-default"
    CURSOR_POINTER = "cursor-pointer"
    CURSOR_WAIT = "cursor-wait"
    CURSOR_TEXT = "cursor-text"
    CURSOR_MOVE = "cursor-move"
    CURSOR_HELP = "cursor-help"
    CURSOR_NOT_ALLOWED = "cursor-not-allowed"


class Outline(Enum):
    """Utilities for controlling an element's outline.
    Tailwind documentation URL: https://tailwindcss.com/docs/outline"""
    OUTLINE_NONE = "outline-none"
    OUTLINE_WHITE = "outline-white"
    OUTLINE_BLACK = "outline-black"


class PointerEvents(Enum):
    """Utilities for controlling whether an element responds to pointer events.
    Tailwind documentation URL: https://tailwindcss.com/docs/pointer-events"""
    POINTER_EVENTS_NONE = "pointer-events-none"
    POINTER_EVENTS_AUTO = "pointer-events-auto"


class Resize(Enum):
    """Utilities for controlling how an element can be resized.
    Tailwind documentation URL: https://tailwindcss.com/docs/resize"""
    RESIZE_NONE = "resize-none"
    RESIZE_Y = "resize-y"
    RESIZE_X = "resize-x"
    RESIZE = "resize"


class UserSelect(Enum):
    """Utilities for controlling whether the user can select text in an element.
    Tailwind documentation URL: https://tailwindcss.com/docs/user-select"""
    SELECT_NONE = "select-none"
    SELECT_TEXT = "select-text"
    SELECT_ALL = "select-all"
    SELECT_AUTO = "select-auto"

