"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class Metaclasses(Enum):
    APPLICATION_NAME = "application-name"
    AUTHOR = "author"
    DESCRIPTION = "description"
    GENERATOR = "generator"
    KEYWORDS = "keywords"
    REFERRER = "referrer"
    THEME_COLOR = "theme-color"

