"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class Fill(Enum):
    """Utilities for styling the fill of SVG elements.
    Tailwind documentation URL: https://tailwindcss.com/docs/fill"""
    FILL_CURRENT = "fill-current"


class Stroke(Enum):
    """Utilities for styling the stroke of SVG elements.
    Tailwind documentation URL: https://tailwindcss.com/docs/stroke"""
    STROKE_CURRENT = "stroke-current"


class StrokeWidth(Enum):
    """Utilities for styling the stroke width of SVG elements.
    Tailwind documentation URL: https://tailwindcss.com/docs/stroke-width"""
    STROKE_0 = "stroke-0"
    STROKE_1 = "stroke-1"
    STROKE_2 = "stroke-2"

