"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class BorderCollapse(Enum):
    """Utilities for controlling whether table borders should collapse or be separated.
    Tailwind documentation URL: https://tailwindcss.com/docs/border-collapse"""
    BORDER_COLLAPSE = "border-collapse"
    BORDER_SEPARATE = "border-separate"


class TableLayout(Enum):
    """Utilities for controlling the table layout algorithm.
    Tailwind documentation URL: https://tailwindcss.com/docs/table-layout"""
    TABLE_AUTO = "table-auto"
    TABLE_FIXED = "table-fixed"

