"""
WARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py
"""
from enum import Enum

class TransitionProperty(Enum):
    """Utilities for controlling which CSS properties transition.
    Tailwind documentation URL: https://tailwindcss.com/docs/transition-property"""
    TRANSITION_NONE = "transition-none"
    TRANSITION_ALL = "transition-all"
    TRANSITION = "transition"
    TRANSITION_COLORS = "transition-colors"
    TRANSITION_OPACITY = "transition-opacity"
    TRANSITION_SHADOW = "transition-shadow"
    TRANSITION_TRANSFORM = "transition-transform"


class TransitionDuration(Enum):
    """Utilities for controlling the duration of CSS transitions.
    Tailwind documentation URL: https://tailwindcss.com/docs/transition-duration"""
    DURATION_75 = "duration-75"
    DURATION_100 = "duration-100"
    DURATION_150 = "duration-150"
    DURATION_200 = "duration-200"
    DURATION_300 = "duration-300"
    DURATION_500 = "duration-500"
    DURATION_700 = "duration-700"
    DURATION_1000 = "duration-1000"


class TransitionTimingFunction(Enum):
    """Utilities for controlling the easing of CSS transitions.
    Tailwind documentation URL: https://tailwindcss.com/docs/transition-timing-function"""
    EASE_LINEAR = "ease-linear"
    EASE_IN = "ease-in"
    EASE_OUT = "ease-out"
    EASE_IN_OUT = "ease-in-out"


class TransitionDelay(Enum):
    """Utilities for controlling the delay of CSS transitions.
    Tailwind documentation URL: https://tailwindcss.com/docs/transition-delay"""
    DELAY_75 = "delay-75"
    DELAY_100 = "delay-100"
    DELAY_150 = "delay-150"
    DELAY_200 = "delay-200"
    DELAY_300 = "delay-300"
    DELAY_500 = "delay-500"
    DELAY_700 = "delay-700"
    DELAY_1000 = "delay-1000"


class Animation(Enum):
    """Utilities for animating elements with CSS animations.
    Tailwind documentation URL: https://tailwindcss.com/docs/animation"""
    ANIMATE_NONE = "animate-none"
    ANIMATE_SPIN = "animate-spin"
    ANIMATE_PING = "animate-ping"
    ANIMATE_PULSE = "animate-pulse"
    ANIMATE_BOUNCE = "animate-bounce"

