import os
import requests
from bs4 import BeautifulSoup

stupid_template = """
class {NAME}(Enum):
{DOCS}{BLAHBLAH}
"""


def magic_text(text):
    return str(text).upper().replace("-", "_")


def gen_from_list(name, lst, docs = None):
    totalstring = []
    for i in lst:
        totalstring.append("    {} = \"{}\"".format(magic_text(i), i))
    doc_write=""
    if docs:
        doc_write = "    \"\"\"{}\"\"\"\n".format(docs)
    return stupid_template.format(NAME=name, DOCS=doc_write, BLAHBLAH="\n".join(totalstring))


def grab_page(address):
    r = requests.get(address)
    if r.status_code == 200:
        return r.content
    else:
        print("Bad url", address)
        return ""


def grab_class_list(content):
    page = BeautifulSoup(content, features="html.parser")
    table_elements = page.find("table").find_all('td', class_="text-violet-600")
    return [i.contents[0] for i in table_elements]


def grab_description(content):
    page = BeautifulSoup(content, features="html.parser")
    description = page.find("p", class_="mt-1 text-lg text-gray-500").contents[0]
    return description


def full_pipe(page):
    content = grab_page(page)
    return (grab_class_list(content), grab_description(content))


def process_name(url):
    tail_name = os.path.split(url)[1]
    return "".join([i.capitalize() for i in tail_name.split("-")])

Typography = ["https://tailwindcss.com/docs/font-family",
            "https://tailwindcss.com/docs/font-size",
            "https://tailwindcss.com/docs/font-smoothing",
            "https://tailwindcss.com/docs/font-style",
            "https://tailwindcss.com/docs/font-weight",
            "https://tailwindcss.com/docs/font-variant-numeric",
            "https://tailwindcss.com/docs/letter-spacing",
            "https://tailwindcss.com/docs/line-height",
            "https://tailwindcss.com/docs/list-style-type",
            "https://tailwindcss.com/docs/list-style-position",
            "https://tailwindcss.com/docs/placeholder-color",
            "https://tailwindcss.com/docs/placeholder-opacity",
            "https://tailwindcss.com/docs/text-align",
            "https://tailwindcss.com/docs/text-color",
            "https://tailwindcss.com/docs/text-opacity",
            "https://tailwindcss.com/docs/text-decoration",
            "https://tailwindcss.com/docs/text-transform",
            "https://tailwindcss.com/docs/text-overflow",
            "https://tailwindcss.com/docs/vertical-align",
            "https://tailwindcss.com/docs/whitespace",
            "https://tailwindcss.com/docs/word-break"]

print("===./src/typography.py===")
with open("./src/typography.py", "w") as f:
    f.write("\"\"\"\nWARNING: THIS FILE IS AUTOMATICALLY GENERATED FROM _gen_everything.py\n\"\"\"")
    f.write("\n")
    f.write("from enum import Enum")
    f.write("\n")
    for c in Typography:
        url = c
        name = process_name(c)
        print(name)
        #print(url, name)
        fp = full_pipe(url)
        f.write(gen_from_list(name, fp[0], docs=fp[1]))
        f.write("\n")

# for key, value in Typography.items():
#     print(_genstupid.gen_from_list(key, full_pipe(value)))
#     print()